import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "./App.vue";
import router from "./router";
import { useAppearance } from "./stores/appearance";
import "./theme.css";
import "./style.css";
import "./finance.css";
import "./attention.css";
import "./detail.css";
import "./reports.css";
import "./plans.css";
import "./shell.css";
const pinia = createPinia();
const app = createApp(App).use(pinia);
useAppearance(pinia);
app.use(router).mount("#app");
